2020-07-04 00:53:40,522 ERROR 42626 [-/127.0.0.1/-/0ms GET /] nodejs.Error: Arguments must be aggregate pipeline operators
    at Aggregate.append (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/aggregate.js:141:11)
    at new Aggregate (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/aggregate.js:55:17)
    at Function.aggregate (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/model.js:3975:21)
    at AccessService.menuListTree (/Users/xiaoqiao/Documents/api/app/service/access.js:8:47)
    at AccessController.menuListTree (/Users/xiaoqiao/Documents/api/app/controller/access.js:39:40)
    at Object.callFn (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xiaoqiao/Documents/api/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xiaoqiao/Documents/api/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xiaoqiao/Documents/api/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xiaoqiao/Documents/api/node_modules/koa-compose/index.js:45:18)
    at middleware (/Users/xiaoqiao/Documents/api/node_modules/koa-jwt2/lib/index.js:145:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/xiaoqiao/Documents/api/app/middleware/errorHandler.js:6:7
    at async /Users/xiaoqiao/Documents/api/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xframe.js:7:5)

pid: 42626
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-04 01:43:38,096 ERROR 43144 [-/127.0.0.1/-/0ms GET /] nodejs.ReferenceError: ctx is not defined
    at searchList (/Users/xiaoqiao/Documents/api/app/service/access.js:21:3)
    at AccessService.menuListTree (/Users/xiaoqiao/Documents/api/app/service/access.js:8:21)
    at AccessController.menuListTree (/Users/xiaoqiao/Documents/api/app/controller/access.js:39:40)
    at Object.callFn (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xiaoqiao/Documents/api/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xiaoqiao/Documents/api/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xiaoqiao/Documents/api/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xiaoqiao/Documents/api/node_modules/koa-compose/index.js:45:18)
    at middleware (/Users/xiaoqiao/Documents/api/node_modules/koa-jwt2/lib/index.js:145:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/xiaoqiao/Documents/api/app/middleware/errorHandler.js:6:7
    at async /Users/xiaoqiao/Documents/api/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)

pid: 43144
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-04 01:49:32,129 ERROR 43249 [-/127.0.0.1/-/0ms GET /] nodejs.TypeError: Cannot read property 'length' of undefined
    at AccessService.menuListTree (/Users/xiaoqiao/Documents/api/app/service/access.js:9:34)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async AccessController.menuListTree (/Users/xiaoqiao/Documents/api/app/controller/access.js:39:15)
    at async middleware (/Users/xiaoqiao/Documents/api/node_modules/koa-jwt2/lib/index.js:145:5)
    at async /Users/xiaoqiao/Documents/api/app/middleware/errorHandler.js:6:7
    at async /Users/xiaoqiao/Documents/api/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)
    at async noopen (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/noopen.js:8:5)
    at async session (/Users/xiaoqiao/Documents/api/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/Users/xiaoqiao/Documents/api/node_modules/koa-bodyparser/index.js:95:5)
    at async /Users/xiaoqiao/Documents/api/node_modules/koa-static-cache/index.js:41:56
    at async notfound (/Users/xiaoqiao/Documents/api/node_modules/egg/app/middleware/notfound.js:5:5)
    at async meta (/Users/xiaoqiao/Documents/api/node_modules/egg/app/middleware/meta.js:12:5)
    at async cors (/Users/xiaoqiao/Documents/api/node_modules/@koa/cors/index.js:56:32)

pid: 43249
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-04 01:50:23,003 ERROR 43295 [-/127.0.0.1/-/0ms GET /] nodejs.TypeError: Cannot read property 'length' of undefined
    at AccessService.menuListTree (/Users/xiaoqiao/Documents/api/app/service/access.js:9:33)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async AccessController.menuListTree (/Users/xiaoqiao/Documents/api/app/controller/access.js:39:15)
    at async middleware (/Users/xiaoqiao/Documents/api/node_modules/koa-jwt2/lib/index.js:145:5)
    at async /Users/xiaoqiao/Documents/api/app/middleware/errorHandler.js:6:7
    at async /Users/xiaoqiao/Documents/api/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)
    at async noopen (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/noopen.js:8:5)
    at async session (/Users/xiaoqiao/Documents/api/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/Users/xiaoqiao/Documents/api/node_modules/koa-bodyparser/index.js:95:5)
    at async /Users/xiaoqiao/Documents/api/node_modules/koa-static-cache/index.js:41:56
    at async notfound (/Users/xiaoqiao/Documents/api/node_modules/egg/app/middleware/notfound.js:5:5)
    at async meta (/Users/xiaoqiao/Documents/api/node_modules/egg/app/middleware/meta.js:12:5)
    at async cors (/Users/xiaoqiao/Documents/api/node_modules/@koa/cors/index.js:56:32)

pid: 43295
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-04 01:52:47,322 ERROR 43319 [-/127.0.0.1/-/0ms GET /] nodejs.ReferenceError: module_id is not defined
    at searchList (/Users/xiaoqiao/Documents/api/app/service/access.js:29:66)
    at AccessService.menuListTree (/Users/xiaoqiao/Documents/api/app/service/access.js:12:30)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async AccessController.menuListTree (/Users/xiaoqiao/Documents/api/app/controller/access.js:39:15)
    at async middleware (/Users/xiaoqiao/Documents/api/node_modules/koa-jwt2/lib/index.js:145:5)
    at async /Users/xiaoqiao/Documents/api/app/middleware/errorHandler.js:6:7
    at async /Users/xiaoqiao/Documents/api/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)
    at async noopen (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/noopen.js:8:5)
    at async session (/Users/xiaoqiao/Documents/api/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/Users/xiaoqiao/Documents/api/node_modules/koa-bodyparser/index.js:95:5)
    at async /Users/xiaoqiao/Documents/api/node_modules/koa-static-cache/index.js:41:56
    at async notfound (/Users/xiaoqiao/Documents/api/node_modules/egg/app/middleware/notfound.js:5:5)
    at async meta (/Users/xiaoqiao/Documents/api/node_modules/egg/app/middleware/meta.js:12:5)

pid: 43319
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-04 01:56:28,339 ERROR 43356 [-/127.0.0.1/-/0ms GET /] nodejs.TypeError: Cannot read property 'module_id' of undefined
    at AccessService.menuListTree (/Users/xiaoqiao/Documents/api/app/service/access.js:11:44)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async AccessController.menuListTree (/Users/xiaoqiao/Documents/api/app/controller/access.js:39:15)
    at async middleware (/Users/xiaoqiao/Documents/api/node_modules/koa-jwt2/lib/index.js:145:5)
    at async /Users/xiaoqiao/Documents/api/app/middleware/errorHandler.js:6:7
    at async /Users/xiaoqiao/Documents/api/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)
    at async noopen (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/noopen.js:8:5)
    at async session (/Users/xiaoqiao/Documents/api/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/Users/xiaoqiao/Documents/api/node_modules/koa-bodyparser/index.js:95:5)
    at async /Users/xiaoqiao/Documents/api/node_modules/koa-static-cache/index.js:41:56
    at async notfound (/Users/xiaoqiao/Documents/api/node_modules/egg/app/middleware/notfound.js:5:5)
    at async meta (/Users/xiaoqiao/Documents/api/node_modules/egg/app/middleware/meta.js:12:5)
    at async cors (/Users/xiaoqiao/Documents/api/node_modules/@koa/cors/index.js:56:32)

pid: 43356
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-04 01:57:26,793 ERROR 43370 [-/127.0.0.1/-/1ms GET /] nodejs.ReferenceError: module_id is not defined
    at searchList (/Users/xiaoqiao/Documents/api/app/service/access.js:28:66)
    at AccessService.menuListTree (/Users/xiaoqiao/Documents/api/app/service/access.js:11:28)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async AccessController.menuListTree (/Users/xiaoqiao/Documents/api/app/controller/access.js:39:15)
    at async middleware (/Users/xiaoqiao/Documents/api/node_modules/koa-jwt2/lib/index.js:145:5)
    at async /Users/xiaoqiao/Documents/api/app/middleware/errorHandler.js:6:7
    at async /Users/xiaoqiao/Documents/api/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)
    at async noopen (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/noopen.js:8:5)
    at async session (/Users/xiaoqiao/Documents/api/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/Users/xiaoqiao/Documents/api/node_modules/koa-bodyparser/index.js:95:5)
    at async /Users/xiaoqiao/Documents/api/node_modules/koa-static-cache/index.js:41:56
    at async notfound (/Users/xiaoqiao/Documents/api/node_modules/egg/app/middleware/notfound.js:5:5)
    at async meta (/Users/xiaoqiao/Documents/api/node_modules/egg/app/middleware/meta.js:12:5)

pid: 43370
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-04 01:59:12,596 ERROR 43394 [-/127.0.0.1/-/0ms GET /] nodejs.ReferenceError: module_id is not defined
    at searchList (/Users/xiaoqiao/Documents/api/app/service/access.js:33:66)
    at AccessService.menuListTree (/Users/xiaoqiao/Documents/api/app/service/access.js:13:32)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async AccessController.menuListTree (/Users/xiaoqiao/Documents/api/app/controller/access.js:39:15)
    at async middleware (/Users/xiaoqiao/Documents/api/node_modules/koa-jwt2/lib/index.js:145:5)
    at async /Users/xiaoqiao/Documents/api/app/middleware/errorHandler.js:6:7
    at async /Users/xiaoqiao/Documents/api/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)
    at async noopen (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/noopen.js:8:5)
    at async session (/Users/xiaoqiao/Documents/api/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/Users/xiaoqiao/Documents/api/node_modules/koa-bodyparser/index.js:95:5)
    at async /Users/xiaoqiao/Documents/api/node_modules/koa-static-cache/index.js:41:56
    at async notfound (/Users/xiaoqiao/Documents/api/node_modules/egg/app/middleware/notfound.js:5:5)
    at async meta (/Users/xiaoqiao/Documents/api/node_modules/egg/app/middleware/meta.js:12:5)

pid: 43394
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-04 04:00:47,652 ERROR 40968 nodejs.ClusterClientNoResponseError: client no response in 7205969ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xiaoqiao/Documents/api/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 40968
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-05 17:48:22,753 ERROR 40968 nodejs.ClusterClientNoResponseError: client no response in 136055063ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xiaoqiao/Documents/api/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 40968
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-05 18:52:45,053 ERROR 40968 nodejs.ClusterClientNoResponseError: client no response in 301690ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xiaoqiao/Documents/api/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 40968
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-05 18:58:26,769 ERROR 40968 nodejs.ClusterClientNoResponseError: client no response in 301710ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xiaoqiao/Documents/api/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 40968
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-05 19:04:13,554 ERROR 40968 nodejs.ClusterClientNoResponseError: client no response in 306758ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xiaoqiao/Documents/api/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 40968
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-05 19:09:35,281 ERROR 40968 nodejs.ClusterClientNoResponseError: client no response in 301713ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xiaoqiao/Documents/api/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 40968
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-05 19:15:16,972 ERROR 40968 nodejs.ClusterClientNoResponseError: client no response in 301665ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xiaoqiao/Documents/api/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 40968
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-05 19:21:03,876 ERROR 40968 nodejs.ClusterClientNoResponseError: client no response in 306887ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xiaoqiao/Documents/api/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 40968
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-05 19:54:17,370 ERROR 40968 nodejs.ClusterClientNoResponseError: client no response in 1953469ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xiaoqiao/Documents/api/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 40968
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-05 21:32:13,173 ERROR 44317 [-/127.0.0.1/-/1ms GET /] nodejs.TypeError: ctx.model.Access.aggregate(...).populate is not a function
    at searchList (/Users/xiaoqiao/Documents/api/app/service/access.js:34:6)
    at AccessService.menuListTree (/Users/xiaoqiao/Documents/api/app/service/access.js:8:21)
    at AccessController.menuListTree (/Users/xiaoqiao/Documents/api/app/controller/access.js:39:40)
    at Object.callFn (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xiaoqiao/Documents/api/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xiaoqiao/Documents/api/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xiaoqiao/Documents/api/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xiaoqiao/Documents/api/node_modules/koa-compose/index.js:45:18)
    at middleware (/Users/xiaoqiao/Documents/api/node_modules/koa-jwt2/lib/index.js:145:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/xiaoqiao/Documents/api/app/middleware/errorHandler.js:6:7
    at async /Users/xiaoqiao/Documents/api/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)

pid: 44317
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-05 22:47:49,125 ERROR 40968 nodejs.ClusterClientNoResponseError: client no response in 82095ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xiaoqiao/Documents/api/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 40968
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-05 23:08:51,603 ERROR 45175 [-/127.0.0.1/-/0ms GET /] nodejs.CastError: Cast to ObjectId failed for value "0" at path "_id" for model "Access"
    at model.Query.exec (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/query.js:4351:21)
    at model.Query.Query.then (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/query.js:4443:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
messageFormat: undefined
stringValue: "\"0\""
kind: "ObjectId"
value: 0
path: "_id"
reason: {}
pid: 45175
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-05 23:08:53,582 ERROR 45175 [-/127.0.0.1/-/0ms GET /] nodejs.CastError: Cast to ObjectId failed for value "0" at path "_id" for model "Access"
    at model.Query.exec (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/query.js:4351:21)
    at model.Query.Query.then (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/query.js:4443:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
messageFormat: undefined
stringValue: "\"0\""
kind: "ObjectId"
value: 0
path: "_id"
reason: {}
pid: 45175
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-05 23:09:13,593 ERROR 45191 [-/127.0.0.1/-/0ms GET /] nodejs.CastError: Cast to ObjectId failed for value "0" at path "_id" for model "Access"
    at model.Query.exec (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/query.js:4351:21)
    at model.Query.Query.then (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/query.js:4443:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
messageFormat: undefined
stringValue: "\"0\""
kind: "ObjectId"
value: 0
path: "_id"
reason: {}
pid: 45191
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-05 23:11:27,928 ERROR 45210 [-/127.0.0.1/-/0ms GET /] nodejs.CastError: Cast to ObjectId failed for value "0" at path "_id" for model "Access"
    at model.Query.exec (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/query.js:4351:21)
    at model.Query.Query.then (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/query.js:4443:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
messageFormat: undefined
stringValue: "\"0\""
kind: "ObjectId"
value: 0
path: "_id"
reason: {}
pid: 45210
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-05 23:11:52,860 ERROR 45225 [-/127.0.0.1/-/1ms GET /] nodejs.CastError: Cast to ObjectId failed for value "0" at path "_id" for model "Access"
    at model.Query.exec (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/query.js:4351:21)
    at model.Query.Query.then (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/query.js:4443:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
messageFormat: undefined
stringValue: "\"0\""
kind: "ObjectId"
value: 0
path: "_id"
reason: {}
pid: 45225
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-05 23:11:53,677 ERROR 45225 [-/127.0.0.1/-/0ms GET /] nodejs.CastError: Cast to ObjectId failed for value "0" at path "_id" for model "Access"
    at model.Query.exec (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/query.js:4351:21)
    at model.Query.Query.then (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/query.js:4443:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
messageFormat: undefined
stringValue: "\"0\""
kind: "ObjectId"
value: 0
path: "_id"
reason: {}
pid: 45225
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-05 23:16:24,368 ERROR 45333 [-/127.0.0.1/-/0ms GET /] nodejs.ReferenceError: id is not defined
    at AccessService.getList (/Users/xiaoqiao/Documents/api/app/service/access.js:11:22)
    at AccessController.index (/Users/xiaoqiao/Documents/api/app/controller/access.js:17:40)
    at Object.callFn (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xiaoqiao/Documents/api/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xiaoqiao/Documents/api/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xiaoqiao/Documents/api/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xiaoqiao/Documents/api/node_modules/koa-compose/index.js:45:18)
    at middleware (/Users/xiaoqiao/Documents/api/node_modules/koa-jwt2/lib/index.js:145:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/xiaoqiao/Documents/api/app/middleware/errorHandler.js:6:7
    at async /Users/xiaoqiao/Documents/api/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)
    at async noopen (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/noopen.js:8:5)

pid: 45333
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-06 01:50:47,612 ERROR 40968 nodejs.ClusterClientNoResponseError: client no response in 6902377ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xiaoqiao/Documents/api/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 40968
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-06 03:51:46,446 ERROR 40968 nodejs.ClusterClientNoResponseError: client no response in 7258786ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xiaoqiao/Documents/api/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 40968
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-06 04:03:56,886 ERROR 40968 nodejs.ClusterClientNoResponseError: client no response in 730398ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xiaoqiao/Documents/api/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 40968
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-06 06:05:01,198 ERROR 40968 nodejs.ClusterClientNoResponseError: client no response in 7264301ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xiaoqiao/Documents/api/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 40968
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-06 07:44:41,957 ERROR 40968 nodejs.ClusterClientNoResponseError: client no response in 5980697ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xiaoqiao/Documents/api/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 40968
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-06 07:45:55,836 ERROR 40968 nodejs.ClusterClientNoResponseError: client no response in 73735ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xiaoqiao/Documents/api/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 40968
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-06 11:56:27,603 ERROR 40968 nodejs.ClusterClientNoResponseError: client no response in 15031722ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xiaoqiao/Documents/api/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 40968
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-06 16:45:05,652 ERROR 40968 nodejs.ClusterClientNoResponseError: client no response in 17318013ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xiaoqiao/Documents/api/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 40968
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-06 18:23:33,411 ERROR 40968 nodejs.ClusterClientNoResponseError: client no response in 5907673ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xiaoqiao/Documents/api/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 40968
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-06 18:56:59,812 ERROR 46404 [-/127.0.0.1/-/0ms GET /] nodejs.TypeError: need object type rule
    at Parameter.validate (/Users/xiaoqiao/Documents/api/node_modules/parameter/index.js:56:13)
    at Object.validate (/Users/xiaoqiao/Documents/api/node_modules/egg-validate/app/extend/context.js:12:39)
    at MenuController.create (/Users/xiaoqiao/Documents/api/app/controller/menu.js:17:9)
    at Object.callFn (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xiaoqiao/Documents/api/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xiaoqiao/Documents/api/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xiaoqiao/Documents/api/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xiaoqiao/Documents/api/node_modules/koa-compose/index.js:45:18)
    at middleware (/Users/xiaoqiao/Documents/api/node_modules/koa-jwt2/lib/index.js:145:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/xiaoqiao/Documents/api/app/middleware/errorHandler.js:6:7
    at async /Users/xiaoqiao/Documents/api/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)

pid: 46404
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-06 18:58:21,275 ERROR 46404 [-/127.0.0.1/-/0ms GET /] nodejs.TypeError: need object type rule
    at Parameter.validate (/Users/xiaoqiao/Documents/api/node_modules/parameter/index.js:56:13)
    at Object.validate (/Users/xiaoqiao/Documents/api/node_modules/egg-validate/app/extend/context.js:12:39)
    at MenuController.create (/Users/xiaoqiao/Documents/api/app/controller/menu.js:17:9)
    at Object.callFn (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xiaoqiao/Documents/api/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xiaoqiao/Documents/api/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xiaoqiao/Documents/api/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xiaoqiao/Documents/api/node_modules/koa-compose/index.js:45:18)
    at middleware (/Users/xiaoqiao/Documents/api/node_modules/koa-jwt2/lib/index.js:145:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/xiaoqiao/Documents/api/app/middleware/errorHandler.js:6:7
    at async /Users/xiaoqiao/Documents/api/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)

pid: 46404
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-06 18:59:10,636 ERROR 46456 [-/127.0.0.1/-/0ms GET /] nodejs.ValidationError: Menu validation failed: url: Path `url` is required.
    at model.Document.invalidate (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/document.js:2574:32)
    at /Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/document.js:2394:17
    at /Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/schematype.js:1181:9
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
errors: {"url":{"properties":{"message":"Path `url` is required.","type":"required","path":"url","value":""},"kind":"required","path":"url","value":""}}
_message: "Menu validation failed"
pid: 46456
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-06 19:05:40,076 ERROR 46584 [-/127.0.0.1/-/1ms GET /] nodejs.ReferenceError: data is not defined
    at MenuController.index (/Users/xiaoqiao/Documents/api/app/controller/menu.js:17:43)
    at Object.callFn (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xiaoqiao/Documents/api/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xiaoqiao/Documents/api/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xiaoqiao/Documents/api/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xiaoqiao/Documents/api/node_modules/koa-compose/index.js:45:18)
    at middleware (/Users/xiaoqiao/Documents/api/node_modules/koa-jwt2/lib/index.js:145:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/xiaoqiao/Documents/api/app/middleware/errorHandler.js:6:7
    at async /Users/xiaoqiao/Documents/api/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)
    at async noopen (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/noopen.js:8:5)
    at async session (/Users/xiaoqiao/Documents/api/node_modules/koa-session/index.js:41:7)

pid: 46584
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-06 19:34:44,490 ERROR 46940 [-/127.0.0.1/-/0ms GET /] nodejs.ReferenceError: BBB is not defined
    at MenuService.list (/Users/xiaoqiao/Documents/api/app/service/menu.js:59:5)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async MenuController.index (/Users/xiaoqiao/Documents/api/app/controller/menu.js:17:15)
    at async middleware (/Users/xiaoqiao/Documents/api/node_modules/koa-jwt2/lib/index.js:145:5)
    at async /Users/xiaoqiao/Documents/api/app/middleware/errorHandler.js:6:7
    at async /Users/xiaoqiao/Documents/api/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)
    at async noopen (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/noopen.js:8:5)
    at async session (/Users/xiaoqiao/Documents/api/node_modules/koa-session/index.js:41:7)
    at async bodyParser (/Users/xiaoqiao/Documents/api/node_modules/koa-bodyparser/index.js:95:5)
    at async /Users/xiaoqiao/Documents/api/node_modules/koa-static-cache/index.js:41:56
    at async notfound (/Users/xiaoqiao/Documents/api/node_modules/egg/app/middleware/notfound.js:5:5)
    at async meta (/Users/xiaoqiao/Documents/api/node_modules/egg/app/middleware/meta.js:12:5)
    at async cors (/Users/xiaoqiao/Documents/api/node_modules/@koa/cors/index.js:56:32)

pid: 46940
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-06 19:55:52,465 ERROR 47269 [-/127.0.0.1/-/1ms GET /] nodejs.CastError: Cast to ObjectId failed for value "f0306780cb13fb60296ecde 5f03068f0cb13fb60296ecdf" at path "_id" for model "Menu"
    at model.Query.exec (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/query.js:4351:21)
    at model.Query.Query.then (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/query.js:4443:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
messageFormat: undefined
stringValue: "\"f0306780cb13fb60296ecde 5f03068f0cb13fb60296ecdf\""
kind: "ObjectId"
value: "f0306780cb13fb60296ecde 5f03068f0cb13fb60296ecdf"
path: "_id"
reason: {}
pid: 47269
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-06 21:18:34,335 ERROR 40968 nodejs.ClusterClientNoResponseError: client no response in 1101983ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xiaoqiao/Documents/api/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 40968
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-06 22:18:18,469 ERROR 40968 nodejs.ClusterClientNoResponseError: client no response in 2023852ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xiaoqiao/Documents/api/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 40968
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-06 22:20:58,100 ERROR 40968 nodejs.ClusterClientNoResponseError: client no response in 119614ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xiaoqiao/Documents/api/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 40968
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-06 22:22:48,003 ERROR 40968 nodejs.ClusterClientNoResponseError: client no response in 109900ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xiaoqiao/Documents/api/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 40968
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-06 22:24:28,143 ERROR 40968 nodejs.ClusterClientNoResponseError: client no response in 60121ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xiaoqiao/Documents/api/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 40968
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-07 17:08:27,114 ERROR 50605 [-/127.0.0.1/-/0ms GET /] nodejs.OverwriteModelError: Cannot overwrite `Menu` model once compiled.
    at Mongoose.model (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/index.js:524:13)
    at module.exports (/Users/xiaoqiao/Documents/api/app/model/menu.js:24:19)
    at getExports (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/loader/file_loader.js:220:15)
    at FileLoader.parse (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/loader/file_loader.js:158:25)
    at FileLoader.load (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/loader/file_loader.js:67:24)
    at AppWorkerLoader.loadToApp (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/loader/egg_loader.js:388:25)
    at loadModelToApp (/Users/xiaoqiao/Documents/api/node_modules/egg-mongoose/lib/mongoose.js:111:14)
    at /Users/xiaoqiao/Documents/api/node_modules/egg-mongoose/lib/mongoose.js:50:7
    at Object.callFn (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/utils/index.js:44:42)
    at /Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/lifecycle.js:256:13
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

pid: 50605
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-07 17:59:19,299 ERROR 51067 [-/127.0.0.1/-/0ms GET /] nodejs.TypeError: rule type must be one of number, int, integer, string, id, date, dateTime, datetime, boolean, bool, array, object, enum, email, password, url, but the following type was passed: undefined
    at Parameter.validate (/Users/xiaoqiao/Documents/api/node_modules/parameter/index.js:106:15)
    at Object.validate (/Users/xiaoqiao/Documents/api/node_modules/egg-validate/app/extend/context.js:12:39)
    at ActionController.create (/Users/xiaoqiao/Documents/api/app/controller/action.js:22:9)
    at Object.callFn (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xiaoqiao/Documents/api/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xiaoqiao/Documents/api/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xiaoqiao/Documents/api/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xiaoqiao/Documents/api/node_modules/koa-compose/index.js:45:18)
    at middleware (/Users/xiaoqiao/Documents/api/node_modules/koa-jwt2/lib/index.js:145:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/xiaoqiao/Documents/api/app/middleware/errorHandler.js:6:7
    at async /Users/xiaoqiao/Documents/api/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)

pid: 51067
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-07 18:00:01,310 ERROR 51110 [-/127.0.0.1/-/0ms GET /] nodejs.TypeError: rule type must be one of number, int, integer, string, id, date, dateTime, datetime, boolean, bool, array, object, enum, email, password, url, but the following type was passed: undefined
    at Parameter.validate (/Users/xiaoqiao/Documents/api/node_modules/parameter/index.js:106:15)
    at Object.validate (/Users/xiaoqiao/Documents/api/node_modules/egg-validate/app/extend/context.js:12:39)
    at ActionController.create (/Users/xiaoqiao/Documents/api/app/controller/action.js:22:9)
    at Object.callFn (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xiaoqiao/Documents/api/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xiaoqiao/Documents/api/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xiaoqiao/Documents/api/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xiaoqiao/Documents/api/node_modules/koa-compose/index.js:45:18)
    at middleware (/Users/xiaoqiao/Documents/api/node_modules/koa-jwt2/lib/index.js:145:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/xiaoqiao/Documents/api/app/middleware/errorHandler.js:6:7
    at async /Users/xiaoqiao/Documents/api/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)

pid: 51110
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-07 18:00:53,821 ERROR 51110 [-/127.0.0.1/-/0ms GET /] nodejs.TypeError: rule type must be one of number, int, integer, string, id, date, dateTime, datetime, boolean, bool, array, object, enum, email, password, url, but the following type was passed: undefined
    at Parameter.validate (/Users/xiaoqiao/Documents/api/node_modules/parameter/index.js:106:15)
    at Object.validate (/Users/xiaoqiao/Documents/api/node_modules/egg-validate/app/extend/context.js:12:39)
    at ActionController.create (/Users/xiaoqiao/Documents/api/app/controller/action.js:22:9)
    at Object.callFn (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xiaoqiao/Documents/api/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xiaoqiao/Documents/api/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xiaoqiao/Documents/api/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xiaoqiao/Documents/api/node_modules/koa-compose/index.js:45:18)
    at middleware (/Users/xiaoqiao/Documents/api/node_modules/koa-jwt2/lib/index.js:145:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/xiaoqiao/Documents/api/app/middleware/errorHandler.js:6:7
    at async /Users/xiaoqiao/Documents/api/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)

pid: 51110
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-07 18:01:53,003 ERROR 51150 [-/127.0.0.1/-/0ms GET /] nodejs.ValidationError: Action validation failed: ation_code: Path `ation_code` is required.
    at model.Document.invalidate (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/document.js:2574:32)
    at /Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/document.js:2394:17
    at /Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/schematype.js:1181:9
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
errors: {"ation_code":{"properties":{"message":"Path `ation_code` is required.","type":"required","path":"ation_code"},"kind":"required","path":"ation_code"}}
_message: "Action validation failed"
pid: 51150
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-07 18:16:47,956 ERROR 51396 [-/127.0.0.1/-/0ms GET /] nodejs.ReferenceError: ctx is not defined
    at ActionService.list (/Users/xiaoqiao/Documents/api/app/service/action.js:23:17)
    at ActionController.index (/Users/xiaoqiao/Documents/api/app/controller/action.js:19:40)
    at Object.callFn (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/xiaoqiao/Documents/api/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/xiaoqiao/Documents/api/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/xiaoqiao/Documents/api/node_modules/koa-compose/index.js:44:32)
    at next (/Users/xiaoqiao/Documents/api/node_modules/koa-compose/index.js:45:18)
    at middleware (/Users/xiaoqiao/Documents/api/node_modules/koa-jwt2/lib/index.js:145:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /Users/xiaoqiao/Documents/api/app/middleware/errorHandler.js:6:7
    at async /Users/xiaoqiao/Documents/api/node_modules/egg-development/app/middleware/egg_loader_trace.js:9:50
    at async xframe (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xframe.js:7:5)
    at async xssProtection (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/xssProtection.js:7:5)
    at async nosniff (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/nosniff.js:8:5)
    at async noopen (/Users/xiaoqiao/Documents/api/node_modules/egg-security/lib/middlewares/noopen.js:8:5)

pid: 51396
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-08 20:07:13,470 ERROR 55274 [-/127.0.0.1/-/0ms GET /] nodejs.OverwriteModelError: Cannot overwrite `Role` model once compiled.
    at Mongoose.model (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/index.js:524:13)
    at module.exports (/Users/xiaoqiao/Documents/api/app/model/role_action.js:19:19)
    at getExports (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/loader/file_loader.js:220:15)
    at FileLoader.parse (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/loader/file_loader.js:158:25)
    at FileLoader.load (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/loader/file_loader.js:67:24)
    at AppWorkerLoader.loadToApp (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/loader/egg_loader.js:388:25)
    at loadModelToApp (/Users/xiaoqiao/Documents/api/node_modules/egg-mongoose/lib/mongoose.js:111:14)
    at /Users/xiaoqiao/Documents/api/node_modules/egg-mongoose/lib/mongoose.js:50:7
    at Object.callFn (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/utils/index.js:44:42)
    at /Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/lifecycle.js:256:13
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

pid: 55274
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-08 20:07:42,341 ERROR 55294 [-/127.0.0.1/-/0ms GET /] nodejs.ReferenceError: RoleSchema is not defined
    at module.exports (/Users/xiaoqiao/Documents/api/app/model/role_action.js:18:33)
    at getExports (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/loader/file_loader.js:220:15)
    at FileLoader.parse (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/loader/file_loader.js:158:25)
    at FileLoader.load (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/loader/file_loader.js:67:24)
    at AppWorkerLoader.loadToApp (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/loader/egg_loader.js:388:25)
    at loadModelToApp (/Users/xiaoqiao/Documents/api/node_modules/egg-mongoose/lib/mongoose.js:111:14)
    at /Users/xiaoqiao/Documents/api/node_modules/egg-mongoose/lib/mongoose.js:50:7
    at Object.callFn (/Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/utils/index.js:44:42)
    at /Users/xiaoqiao/Documents/api/node_modules/egg-core/lib/lifecycle.js:256:13
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

pid: 55294
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-08 20:44:53,470 ERROR 54688 nodejs.ClusterClientNoResponseError: client no response in 410384ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/xiaoqiao/Documents/api/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 54688
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-08 21:25:57,532 ERROR 56423 [-/127.0.0.1/-/1ms GET /] nodejs.CastError: Cast to ObjectId failed for value "rolemenu" at path "_id" for model "Role"
    at model.Query.exec (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/query.js:4351:21)
    at model.Query.Query.then (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/query.js:4443:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
messageFormat: undefined
stringValue: "\"rolemenu\""
kind: "ObjectId"
value: "rolemenu"
path: "_id"
reason: {}
pid: 56423
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-08 21:26:33,511 ERROR 56441 [-/127.0.0.1/-/0ms GET /] nodejs.CastError: Cast to ObjectId failed for value "rolemenu" at path "_id" for model "Role"
    at model.Query.exec (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/query.js:4351:21)
    at model.Query.Query.then (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/query.js:4443:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
messageFormat: undefined
stringValue: "\"rolemenu\""
kind: "ObjectId"
value: "rolemenu"
path: "_id"
reason: {}
pid: 56441
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-08 21:26:37,267 ERROR 56441 [-/127.0.0.1/-/0ms GET /] nodejs.CastError: Cast to ObjectId failed for value "rolemenu" at path "_id" for model "Role"
    at model.Query.exec (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/query.js:4351:21)
    at model.Query.Query.then (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/query.js:4443:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
messageFormat: undefined
stringValue: "\"rolemenu\""
kind: "ObjectId"
value: "rolemenu"
path: "_id"
reason: {}
pid: 56441
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-08 21:27:49,126 ERROR 56450 [-/127.0.0.1/-/0ms GET /] nodejs.CastError: Cast to ObjectId failed for value "rolemenu" at path "_id" for model "Role"
    at model.Query.exec (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/query.js:4351:21)
    at model.Query.Query.then (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/query.js:4443:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
messageFormat: undefined
stringValue: "\"rolemenu\""
kind: "ObjectId"
value: "rolemenu"
path: "_id"
reason: {}
pid: 56450
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-08 21:27:56,435 ERROR 56450 [-/127.0.0.1/-/0ms GET /] nodejs.CastError: Cast to ObjectId failed for value "rolemenu" at path "_id" for model "Role"
    at model.Query.exec (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/query.js:4351:21)
    at model.Query.Query.then (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/query.js:4443:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
messageFormat: undefined
stringValue: "\"rolemenu\""
kind: "ObjectId"
value: "rolemenu"
path: "_id"
reason: {}
pid: 56450
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-08 21:30:08,336 ERROR 56519 [-/127.0.0.1/-/0ms GET /] nodejs.CastError: Cast to ObjectId failed for value "rolemenu" at path "_id" for model "Role"
    at model.Query.exec (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/query.js:4351:21)
    at model.Query.Query.then (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/query.js:4443:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
messageFormat: undefined
stringValue: "\"rolemenu\""
kind: "ObjectId"
value: "rolemenu"
path: "_id"
reason: {}
pid: 56519
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-08 21:30:31,885 ERROR 56519 [-/127.0.0.1/-/0ms GET /] nodejs.CastError: Cast to ObjectId failed for value "rolemenu" at path "_id" for model "Role"
    at model.Query.exec (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/query.js:4351:21)
    at model.Query.Query.then (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/query.js:4443:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
messageFormat: undefined
stringValue: "\"rolemenu\""
kind: "ObjectId"
value: "rolemenu"
path: "_id"
reason: {}
pid: 56519
hostname: xiaoqiaodeMacBook-Pro.local

2020-07-08 21:43:36,137 ERROR 56884 [-/127.0.0.1/-/0ms GET /] nodejs.CastError: Cast to ObjectId failed for value "aID" at path "role_id" for model "RoleMenu"
    at model.Query.exec (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/query.js:4351:21)
    at model.Query.Query.then (/Users/xiaoqiao/Documents/api/node_modules/mongoose/lib/query.js:4443:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
messageFormat: undefined
stringValue: "\"aID\""
kind: "ObjectId"
value: "aID"
path: "role_id"
reason: {}
pid: 56884
hostname: xiaoqiaodeMacBook-Pro.local

